version: "3.7"

services:
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: MS_SQL_Server
    restart: always
    environment:
      SA_PASSWORD: "realyStrongPassword123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"