version: "3.7"

services:
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: ms_sql_server
    restart: always
    env_file:
      - .env
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "1433:1433"
