version: "3.7"

services:
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: ms_sql_server
    restart: always
    env_file:
      - .env
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_PORT}:1433'

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mssql
    env_file:
      - .env
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - PORT=${PORT}
    ports:
      - '${PORT}:3000'