version: "3.7"

services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    restart: always
    env_file:
      - .env
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - PORT=${PORT}
    ports:
      - '${PORT}:${PORT}'